require "user.options"
require "user.keymaps"
require "user.custom_commands"
require "user.plugins"
require "user.colorscheme"
require "user.comment"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.toggleterm"
require "user.lualine"
require "user.impatient"
require "user.whichkey"

require "user.treesitter"
-- require "user.indentline"
-- require "user.autocommands"
